language: rust

env:
    global:
        # Use in deploy
        - PROJECT_NAME=tfs

# Specify all of our different build configs.
matrix:
    # Don't wait for builds that are allowed to fail.
    fast_finish: true

    allow_failures:
        # FIXME(#9): i686-unknown-linux-gnu cross compile is broken
        - env: TARGET=i686-unknown-linux-gnu RUST=stable PKG_CONFIG_ALLOW_CROSS=1

    # Our actual builds
    include:
        # Cross Compiles:

        # Linux i686-unknown-linux-gnu
        # FIXME(#9): pkg-config doesn't pick up fuse
        - os: linux
          sudo: true
          dist: trusty
          env: TARGET=i686-unknown-linux-gnu RUST=stable PKG_CONFIG_ALLOW_CROSS=1
          rust: stable # Only cross-compile from stable
          install:
              - "sudo dpkg --add-architecture i386"
              - "sudo apt-get update || true" # This might fail but we don't care
              - "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libfuse-dev:i386"
              - "bash ci/install.sh"
          addons:
            apt:
              packages:
                # Cross compiler and cross compiled C libraries
                - gcc-multilib

        # OS X i686-apple-darwin
        - os: osx
          env: TARGET=i686-apple-darwin RUST=stable PKG_CONFIG_ALLOW_CROSS=1
          rust: stable # Only cross-compile from stable

        # Linux x86_64-unknown-linux-musl
        - os: linux
          env: TARGET=x86_64-unknown-linux-musl RUST=stable PKG_CONFIG_ALLOW_CROSS=1
          rust: stable
          addons:
            apt:
              packages:
                - libfuse-dev

        # Native compiles:

        # Linux x86_64-unknown-linux-gnu
        - os: linux
          env: TARGET=x86_64-unknown-linux-gnu RUST=stable
          rust: stable
          addons:
            apt:
              packages:
                - libfuse-dev
        - os: linux
          env: TARGET=x86_64-unknown-linux-gnu
          rust: beta
          addons:
            apt:
              packages:
                - libfuse-dev
        - os: linux
          env: TARGET=x86_64-unknown-linux-gnu
          rust: nightly
          addons:
            apt:
              packages:
                - libfuse-dev

        # OS X x86_64-apple-darwin
        - os: osx
          rust: stable
          env: TARGET=x86_64-apple-darwin RUST=stable
        - os: osx
          rust: beta
          env: TARGET=x86_64-apple-darwin
        - os: osx
          rust: nightly
          env: TARGET=x86_64-apple-darwin


install:
    - bash ci/install.sh

before_deploy:
    - bash ci/before_deploy.sh

script:
    - bash ci/script.sh

deploy:
    provider: releases
    api_key:
        secure: "XZ90EEZOEECNbJXgtGvnZF2P6Euk8QIjfhA+yWEHLoThxAOvuQ1puS82BtK7zx3H5+I7DzP5RoxQpZLwSYMSBMOPoT51Jxoq7sYb5PJHsBcMRHHd3Z/Bc7RWC3eezBQPDCoh9zTMDfii8v4bwiA32+JD2zDdoUFPtC9VPaWzEOU+EupEvhMsW/Sw865hUNygNlQgu1j/cunkI1VOKCpfDOxZvu2k3MejPscVnl+VZOyYRYM/YKBWaJBYF8nyFhY2c5XDwjsJhQvwfSsnHPVVmg1VMS9gp1DlazmZomvU0vHaFnTkAEc002YHLWocZYw02EZpuLhnbChRXcavSiJuHtTV/DQKHxW6Bz4lpFUWHasjwvT7b59S066CogZ67XNjNjbcnWLs4dAAZ49Agn5uL8B0gTkNxiW3tvuMOexNpARZFyGEj2FrFFpwbbXDfY3/4ESIH09uwFKHVUl/vl1lQV/sdYJXVLz/R3jztG+yO+XhID4eWsL9R9o95Qz/848Mid+vE2NZSoMsT+Q+98+Pw3Buakl/nkEf0p5iVhl9e//zD5QTwpSpBew4U+J9FSzBNfq2hmh9rT5ZJogLW83DiuxOuGjJ1UVKU60SgFop9ustfcPCDdVI0/1xwm+76Vj/shG+UkOv5ohQ+ofALPLHdQo+6xCA/85A9mdI8bPTWp0="
    file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
    skip_cleanup: true
    on:
        repo: terminalcloud/tfs # Prevent failed deploys on forks
        condition: $RUST = stable
        branch: master
        tags: true

