language: rust

os:
    - linux
    - osx

# Install FUSE on linux
addons:
    apt:
        packages:
            - libfuse-dev

# Install FUSE on OS X
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew update && brew install osxfuse;
    fi

rust:
    - nightly
    - beta
    - stable
