language: rust

os:
    - linux
    - osx

# FIXME: When we land FUSE integration, reactive and figure out OS X too.
# addons:
#     apt:
#         packages:
#             - libfuse-dev

rust:
    - nightly
    - beta
    # FIXME: See #2
    # - stable
