[package]
name = "tfs"
version = "0.1.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]

[dependencies]
scoped-pool = "0.1"
rand = "0.3"
uuid = "0.1"
libc = "0.2"
bit-vec = "0.4"
terminal-linked-hash-map = "0.1"
rwlock2 = "0.1"
crossbeam = "0.2"
atomic-option = "0.0"
threadpool = "0.2"
vec_map = "0.4"
slab = "0.1"
log = "0.3"

[dev-dependencies]
tempfile = "2.0"

