[package]
name = "tfs-fuse-sys"
version = "0.1.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
license = "GPL-3.0+"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
